#!/usr/bin/env python
"""
Ensures the repo is in a fit state before allowing a git push.
"""

import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from types import FunctionType


@dataclass
class Step:
  description: str
  on_pass: FunctionType = lambda: ""
  on_fail: FunctionType = lambda: ""

  def __enter__(self):
    print(f"🪜  {self.description}", end="... ")

  def __exit__(self, exc_type, exc_val, exc_tb):
    if exc_type is not None:
      print("❌")
      if err := str(exc_val):
        # our exceptions are empty, so this should be an actual exception
        print(f"💥 {err}", file=sys.stderr)
      suggestion = self.on_fail()
      if suggestion:
        print("💡 " + suggestion)
      sys.exit(1)
    print("✔️  " + self.on_pass())


def change_to_repo_root():
  with Step("Changing to repo root", on_pass=lambda: os.getcwd()):
    repo_root = subprocess.run(
      ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True
    )
    if repo_root.returncode == 0:
      repo_root_path = repo_root.stdout.strip()
      os.chdir(repo_root_path)
      if repo_root_path not in sys.path:
        sys.path.insert(0, repo_root_path)


def get_push_info():
  local_ref, local_sha, remote_ref, remote_sha = [""] * 4
  lines: list[str] = sys.stdin.read().strip().splitlines()
  for line in lines:
    if not line.strip():
      continue

    parts = line.split()
    if len(parts) < 4:
      continue

    local_ref, local_sha, remote_ref, remote_sha = parts[:4]
  return local_ref, local_sha, remote_ref, remote_sha


def main():
  from dev.check.do_tests_pass.query import DoTestsPass
  from dev.check.is_code_formatted.query import IsCodeFormatted
  from dev.check.is_git_hook_updated.query import IsGitHookUpdated
  from dev.check.is_version_bump_needed.query import IsVersionBumpNeeded
  from dev.check.is_working_dir_clean.query import IsWorkingDirClean

  with Step(
    "Checking if git hook is updated",
    on_fail=lambda: "Run source dev/env.sh --nuke",
  ):
    if not IsGitHookUpdated(Path(__file__)).execute():
      raise RuntimeError()

  with Step(
    "Checking if working directory is clean",
    on_fail=lambda: "Commit or stash your changes",
  ):
    if not IsWorkingDirClean().execute():
      raise RuntimeError()

  with Step(
    "Checking if code is formatted",
    on_fail=lambda: "Run ruff check && ruff format --check",
  ):
    if not IsCodeFormatted(auto_fix=True).execute():
      raise RuntimeError()

  with Step(
    "Checking if tests pass",
    on_fail=lambda: "Fix failing tests",
  ):
    if not DoTestsPass().execute():
      raise RuntimeError()

  with Step(
    "Checking if version bump is needed",
    on_fail=lambda: "Run dev.bump-version",
  ):
    if IsVersionBumpNeeded(*get_push_info()).execute():
      raise RuntimeError()


if __name__ == "__main__":
  change_to_repo_root()
  main()
